node_name = "__required"
node_admin_email = "__required"
magpie_path = "/magpie"
login_home = "login.html"

[terms-and-conditions]

[login-providers]
enable = true
providers = ["CEDA", "DKRZ", "SMHI", "Github", "OpenID", "WSO2", "IPSL", "LLNL"]
